FIND_PATH(LIBMURMUR_INCLUDE_DIR NAMES murmurhash.h)
FIND_LIBRARY(LIBMURMUR_LIBRARY NAMES murmurhash )


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBMURMUR DEFAULT_MSG LIBMURMUR_LIBRARY LIBMURMUR_INCLUDE_DIR )

IF(LIBMURMUR_FOUND)
	SET(MURMUR_LIBRARIES ${LIBMURMUR_LIBRARY} )
	SET(MURMUR_INCLUDE_DIRS ${LIBMURMUR_INCLUDE_DIR})
ELSE(LIBMURMUR_FOUND)
	SET(MURMUR_LIBRARIES)
	SET(MURMUR_INCLUDE_DIRS)
ENDIF(LIBMURMUR_FOUND)