FIND_PATH(LIBCVC4_INCLUDE_DIR NAMES cvc4/cvc4.h)
FIND_LIBRARY(LIBCVC4_LIBRARY NAMES cvc4)
#FIND_LIBRARY(LIBCLN_LIBRARY NAMES cln)


find_path(GMP_INCLUDE_DIR NAMES gmp.h gmpxx.h)
find_library(GMP_LIBRARIES NAMES gmp)

message("${LIBCVC4_INCLUDE_DIR} ${LIBCVC4_LIBRARY}") #${LIBCLN_LIBRARY}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBCVC4 DEFAULT_MSG LIBCVC4_LIBRARY LIBCLN_LIBRARY  LIBCVC4_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBCVC4 DEFAULT_MSG LIBCVC4_LIBRARY LIBCVC4_INCLUDE_DIR)
find_package_handle_standard_args(GMP DEFAULT_MSG GMP_INCLUDE_DIR GMP_LIBRARIES)

mark_as_advanced(GMP_INCLUDE_DIR GMP_LIBRARIES)


IF(LIBCVC4_FOUND)
	SET(CVC4_LIBRARIES ${LIBCVC4_LIBRARY} ${GMP_LIBRARIES})#${LIBCLN_LIBRARY})
	SET(CVC4_INCLUDE_DIRS ${LIBCVC4_INCLUDE_DIR} ${GMP_INCLUDE_DIR})
ELSE(LIBCVC4_FOUND)
		message(FATAL_ERROR "CVC4 not available")
ENDIF(LIBCVC4_FOUND)
