= Woorpje:
Transformation-system-based word equation solving
:toc: left
:stem:

We present a transformation-system-based technique in the framework of string solving, by reformulating a
classical combinatorics on words result, the Lemma of Levi. We further enrich the induced
rules by simplification steps based on results from the combinatorial theory of word equations, as well as by the addition of linear length constraints.
This transformation-system approach cannot solve all equations efficiently by itself, so our final approach integrates existing string solvers, which are called based on heuristics.
Experimental evaluation shows that this technique is useful as an inprocessing method for existing solvers.

== Using Woorpje:
Woorpje is invoked from the command line with `./woorpje --solver 4 equation.eq` where `equation.eq` is the configuration file for Woorpje and the argument --solver uses the transformation system.

=== Simple Example
Using Woorpje to solve the equation `aX = Yb` is as simple as providing the below configuration file to Woorpje.

----
include::examples/exampleLevi.eq[]
----
The lines `Variables` `Terminals` and `Equation` must be written in
that order, and they have the obvious semantics.

[TIP]
It is possible to specify a system of equations, where all equations must be true, by specifying several `Equation` lines


As can be seen from the output below, Woorpje finds a solution to the equation where it sets `X = b` and `Y = a`.
Woorpje also provides a proof that the substitution is correct by outputting the left hand side and right hand side
with substituted variables.

----
include::examples/exampleLevi.out[]
----

=== Linear Constraints
Woorpje supports constraining the set of potential solutions by specifying constraints between linear arithmetic expressions
over the length of the variables. As an example, consider that want solution to `aX = Yb` where `X` is longer than 5,
we can add the constraint  `LinConstraint: [ >= +1|X|, +5]` to the configuration file.
Linear constraints must be specified after the word equations. Giving us the configuration file

----
include::examples/linexampleLevi.eq[]
----

[TIP]
Linear Constraints are specified in prefix form where the comparison operator (`>=,<=, >, <`) is first specified and
after that the left hand side and then the right hand side of comparison.

The output from Woorpje

----
include::examples/linexampleLevi.out[]
----

reveals that there is indeed a solution. It also shows, that Woorpje encoded the word equation problem into SAT three times.

=== Heuristics and Solver Setup
The following information is given inside the help command of woorpje:
----
include::examples/help.out[]
----

By using the parameter `-S` we are able to select one of the SMT solvers listed above. The parameter `--levisheuristics` allows us
to choose a heuristic to call the external solver within the search for a solution of a system of word equations.

1. If `VariableTerminalRatio` is used, the external solver is trigger if  for a transition between two systems of word equations latexmath:[E] and latexmath:[E'] with an
r-function latexmath:[E \xrightarrow{r} E'] the ratio between variables and terminals
changes to an unfortunate extent w.r.t. our rules, meaning for latexmath:[s \in \mathbb{Q}], we have
latexmath:[t(E) = \left(\sum_{e \in E} |e_{|\Sigma}|\right)] and
latexmath:[v(E) = \left(\sum_{e \in E} |e_{|\Gamma}|\right)] and
latexmath:[\frac{t(E)}{v(E)} \cdot s < \frac{t(E')}{v(E')}]. If this
satisfied, we know about a massive increase of letters in the middle of at least one side of the word equation, thus it is unfortunate to apply our rules.
We are able to set the parameter latexmath:[s] by using the parameter `--VarTerminalRation`.

2. If `WaitingListLimitReached` is used, the external solver is trigger if a predefined depth latexmath:[d \in \mathbb{N}] of the transformation system is reached.
    We are able to set the parameter latexmath:[d] by using the parameter `--WaitingLimit`.

3. If `EquationGrowth` is used, the external solver is trigger if  for a transition between two systems of word equations latexmath:[E] and latexmath:[E'] with an
r-function latexmath:[E \xrightarrow{r} E']
the length of each word equation latexmath:[e \in E] increased too quickly, meaning for a factor latexmath:[s \in \mathbb{Q}] we get
latexmath:[\left(\sum_{e \in E} |e|\right) \cdot s < \left(\sum_{e \in E'} |e|\right)]. This gives us an indicator to the
presence of a long solution, where applying our rules might take longer. We are able to set the parameter latexmath:[s] by using the parameter `--growth`.

4. If `EquationLengthExceeded` is used, the external solver is trigger if In a system of word equations E each
equation e in E has exceeded a bound latexmath:[b \in \mathbb{N}]. We are able to set the parameter latexmath:[b] by using the parameter `--eqLength`.

include::benchmarksLevi.adoc[]
== Availability
=== Binary
We distribute the precompiled binary of Woorpje 0.2 for Linux  https://www.informatik.uni-kiel.de/~mku/woorpje/files/woorpje-0_2.zip[here].

=== Benchmarks
The benchmarks in SMT2 and woorpje format are available here:


- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track01.tar.gz[Track I]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track02.tar.gz[Track II]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track03.tar.gz[Track III]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track04.tar.gz[Track IV]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track05.tar.gz[Track V]


== People involved
- https://www.zs.informatik.uni-kiel.de/de/mitarbeiter/mitja-kulczynski[Mitja Kulczynski]
- http://flmanea.blogspot.com/[Florin Manea]
- https://www.zs.informatik.uni-kiel.de/de/mitarbeiter/nowotka[Dirk Nowotka]
- https://www.boegstedpoulsen.dk[Danny Bøgsted Poulsem]


