= Woorpje:
Bounded Word Equation Solver
:toc: left
:stem:

Woorpje is a string solver for bounded word equations, i.e., the length of the strings substituting each variable is
upper bounded by a given integer. Using the existence of these bounds, and the fact that the alphabet of the strings is
finite, allows us to reformulate the question _is this equation solvable_ into a reachability check in a finite automaton.
Preliminary experiments with a simplistic reachability search revealed, however, that the search space quickly becomes intractable.
Thus, Woorpje translates the Bounded Word Equation problem further into a satisfiability problem of propositional logic,
 and uses the award-winning SAT-solver http://www.labri.fr/perso/lsimon/glucose/[Glucose] as its SAT-Solving backend.

== Using Woorpje:
Woorpje is invoked from the command line with `./woorpje equation.eq` where `equation.eq` is the configuration file for Woorpje.

=== Simple Example
Using Woorpje to solve the equation `aX = Yb` is as simple as providing the below configuration file to Woorpje.

----
include::examples/example.eq[]
----
The lines `Variables` `Terminals` and `Equation` must be written in
that order, and they have the obvious semantics. The last line
`SatGlucose(10)` invokes the solver and pass the number 10 as
parameter to the solver.  The `10` informs the solver to try increase
the bound exponentially ten times. If the parameter is `0`, Woorpje will guess a suitable value.

[TIP]
It is possible to specify a system of equations, where all equations must be true, by specifying several `Equation` lines


As can be seen from the output below, Woorpje finds a solution to the equation where it sets `X = b` and `Y = a`.
Woorpje also provides a proof that the substitution is correct by outputting the left hand side and right hand side
with substituted variables.

----
include::examples/example.out[]
----

=== Linear Constraints
Woorpje supports constraining the set of potential solutions by specifying constraints between linear arithmetic expressions
over the length of the variables. As an example, consider that want solution to `aX = Yb` where `X` is longer than 5,
we can add the constraint  `LinConstraint: [ >= +1|X|, +5]` to the configuration file.
Linear constraints must be specified after the word equations. Giving us the configuration file

----
include::examples/linexample.eq[]
----

[TIP]
Linear Constraints are specified in prefix form where the comparison operator (`>=,<=, >, <`) is first specified and
after that the left hand side and then the right hand side of comparison.

The output from Woorpje

----
include::examples/linexample.out[]
----

reveals that there is indeed a solution. It also shows, that Woorpje encoded the word equation problem into SAT three times.

include::benchmarks.adoc[]

== Availability
=== Binary
We distribute the precompiled binary of Woorpje 0.1 for Linux  https://www.informatik.uni-kiel.de/~mku/woorpje/files/woorpje-0_1.zip[here].

=== Benchmarks
The benchmark in SMT2 and woorpje format are available here:


- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track01.tar.gz[Track I]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track02.tar.gz[Track II]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track03.tar.gz[Track III]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track04.tar.gz[Track IV]
- https://www.informatik.uni-kiel.de/~mku/woorpje/files/track05.tar.gz[Track V]


== People involved
- https://www.zs.informatik.uni-kiel.de/de/mitarbeiter/b-sc-joel-day[Joel Day]
- https://www.zs.informatik.uni-kiel.de/de/mitarbeiter/thorsten-ehlers-msc[Thorsten Ehlers]
- https://www.zs.informatik.uni-kiel.de/de/mitarbeiter/mitja-kulczynski[Mitja Kulczynski]
- http://flmanea.blogspot.com/[Florin Manea]
- https://www.zs.informatik.uni-kiel.de/de/mitarbeiter/nowotka[Dirk Nowotka]
- https://www.boegstedpoulsen.dk[Danny Bøgsted Poulsem]


